version: '2'
services:
  javaclient:
    build: .
    links:
      - mysql:mysql
  mysql:
    image: mysql/mysql-server
    environment:
      - MYSQL_DATABASE=toto
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root

